### ISSUE TITLE
Input Field Overflowing

### ISSUE THREAD

**Issue by pastacolsugo** [eutampieri/CaDo#19]
On commit
[https://github.com/eutampieri/CaDo/commit/f7a42d8861d50216e89421b265e3ae98172a5023](url)
I started styling the first input field. 
If I set ```width: 100%;``` it overflows both it's parent `form` and parent `div`.

I guess it isn't the right way to do it.

Check `public/stylesheets/contestSetup.css` @ line 57.

**Comment by eutampieri** [comment]
Closed with the latest commit

**Comment by eutampieri** [comment]
There's however an invalid declaration on line 48 (https://github.com/eutampieri/CaDo/blob/8a52d9306483736eb55768cbd1045db4aa5dcec4/public/stylesheets/contestSetup.css#L48)

**Comment by eutampieri** [comment]
I put sizes in `em` because I think it's the way because it's a relative measurement (not absolute) and so it's better for responsive design
