### ISSUE TITLE
Contest page improvements

### ISSUE THREAD

**Issue by eutampieri** [eutampieri/CaDo#31]
I'd suggest some graphical improvements:
- ![2018-02-10-191121_1440x900_scrot](https://user-images.githubusercontent.com/10284268/36065110-5a2e6498-0e96-11e8-81e2-0e1c7cdd35b8.png) User name is not vertically aligned to middle and I think it should be
- ![2018-02-10-191126_1440x900_scrot](https://user-images.githubusercontent.com/10284268/36065114-6d84de96-0e96-11e8-8822-d0206bc7e6a8.png) Sidebar should follow page scrolling or be tall as the page in order to prevent graphical issues like these.

**Comment by pastacolsugo** [comment]
Yes definitely, that was just a prototype and I made it so that it would look nice on my screen.
Some stuff, among which the user name and user image are just statically padded, so they will need some adjustments.

The sidebar should definitely reach the end of the page, and indeed it did so on my machine.
The CSS grid cell should reach the last row of the page.

**Comment by pastacolsugo** [comment]
<img width="329" alt="schermata 2018-02-10 alle 19 27 57" src="https://user-images.githubusercontent.com/26633506/36065259-8bb9418e-0e98-11e8-80e5-ff3a2f1f95bf.png">

**Comment by eutampieri** [comment]
In which branch did you commit?

**Comment by eutampieri** [comment]
Have you commited the changes? If not, please do this in the `style` branch if it's not a problem for you

**Comment by eutampieri** [comment]
The sidebar length issue does not occur in Chromium. Here are my browser's versions:
Firefox:
```json
{"appCodeName":"Mozilla","appName":"Netscape","appVersion":"5.0 (X11)","platform":"Linux i686","product":"Gecko","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:58.0) Gecko/20100101 Firefox/58.0","ID":"866361c2-85f9-4a22-a2d9-9d1357810bcf"}
```
Chromium:
```json
{"appCodeName":"Mozilla","appName":"Netscape","appVersion":"5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.140 Chrome/64.0.3282.140 Safari/537.36","platform":"Linux i686","product":"Gecko","userAgent":"Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.140 Chrome/64.0.3282.140 Safari/537.36","ID":"e1c36125-c733-451b-8416-c93bc931220f"}
```

**Comment by pastacolsugo** [comment]
`Chrome 64.0.3282.140` on `MacOS X 10.12.6`, everything's fine.

`Firefox 58.0.1 and 58.0.2` on `MacOS X 10.12.6`, body height `17895700px`

**Comment by eutampieri** [comment]
Now it works properly on Firefox and Chrome (at least according to my tests)

**Comment by eutampieri** [comment]
A thing I'd like @pastacolsugo is the sidebar's height in Firefox (it doesn't take advantage of the full vertical space available) and if it's possible make it follow page's scrolling.
Moreover, the username is cropped now, but it's a temporary solution. It would be better if you found a better one...
